### ISSUE TITLE
Make IDL conversion of keyframes use regular dictionary IDL conversion

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#107]
Discussion here: https://bugzilla.mozilla.org/show_bug.cgi?id=1198708#c1

The upshot is: "the order that explicit dictionary members are got off the object doesn't change when you add this semi-open set of additional properties"

It's also more consistent, less spec text, and fixes (I think) the bug described in https://bugzilla.mozilla.org/show_bug.cgi?id=1198708#c27 item (1).

**Comment by birtles** [comment]
I'm going to try and fix this and a bunch of other issues at the same time since they all overlap. Here's a first attempt outline at what we need to do:

1. Define the processing of a single keyframe-like object as something like:

   Arguments:
     "keyframe input"
     "allow lists" boolean flag
     "allow offsets" boolean flag

   * Process "keyframe input" using one of the following dictionary definitions based on the value allow offsets" by applying the procedure here: http://heycam.github.io/webidl/#dictionary-to-es

     If "allow offsets" is true, use:

        ```WebIDL
        dictionary Keyframe {
            double?            offset = null;
            DOMString          easing = "linear";
            CompositeOperation composite;
        };
        ```

     Otherwise, use:

        ```WebIDL
        dictionary KeyframeWithoutOffset {
            DOMString          easing = "linear";
            CompositeOperation composite;
        };

        ```
     Let "keyframe output" be the result of the above operation.

     (There's issue #131 that says maybe we don't need easing and composite in the "allow offsets", i.e. property-indexed keyframe case, but I think actually the intention there is that they allow you set the per-keyframe easing/composite in bulk as opposed to the per-animation setting. I've dropped the default value for composite, however, which should address issue #132.)

     This should fix issue #107.

   * Build up a list of animatable properties (the following is the same as the existing spec)
      * Create a list, "supported properties", of property names and attribute names that can be animated by the implementation.
      * Convert each property name in "supported properties" to the equivalent IDL attribute by applying the CSS property to IDL attribute algorithm.
      * If the user agent supports animation of the float CSS property, replace "float" in "supported properties" with "cssFloat"
      * If the user agent supports animation of the offset attribute of SVG stop elements [SVG2], replace "offset" in "supported properties" with "svgOffset".
        (Google have an outstanding PR to make all animatable attributes have an 'svg-' prefix which I'm about to review)

   * Use the internal [[Enumerate]] operation on keyframe input to iterate over its properties and for each property name that corresponds to a value in "supported properties", add it to a list "additional property names".

     For this, we need to define whether the iterator is snapshotted or if we run add the strings will stepping the iterator. We also need to define what we do with the return value. This is issue #108.

   * Sort "additional property names" lexographically.
   * [[Get]] each of the properties in "additional property names" in order and do the conversion as follows:
     * If "allow lists" is true, convert using type,
       "(DOMString or sequence<DOMString>)", otherwise use "DOMString".
       In both cases perform the conversion with the [TreatNullAs=EmptyString]
       annotation in effect.
       (For the "allow lists" case, null should probably produce an empty
       list?)

         We should probably also do CSS parsing here. We need to fix issue #134 somewhere and implementations are likely to want to store the most compact representation of these values which means parsing them soon. We should say to parse them and store invalid values as their original strings. This should fix issue #130 as well.

     * Add a property to "keyframe output" with the property name as follows:

         cssFloat &rarr; float,
         svg-* &rarr; svg-*
         otherwise &rarr; result of calling the IDL attribute to CSS property algorithm on the name

         Let the value be the result of the conversion above.
         If "allow lists" is true, make sure the result a sequence--i.e. if the result is a DOMString, make a single element list containing the string.

      * Return "keyframe output"

2. Make the type for these keyframe arguments "object?"

3. Define the processing of a keyframes argument as a procedure that returns either a sequence of keyframes, or a SharedKeyframeList object:

    * If the value is null or undefined, return an empty sequence.
    * If the value is a platform object that implements SharedKeyframeList, return that object.
    * If the value is iterable...
      Question: What's the correct way to spec if something is iterable?

        * Let "processed frames" be an empty sequence.
        * Iterate over the object...
          Question: What's the correct way to spec this. I guess we basically just use the terminology from WebIDL?

          For each step of the iterator run the procedure defined above (item 1) for the current value, with "allow lists" as false and "allow offsets" as true.
          Append the result to "process "processed frame".
        * If "processed frames" is not loosely sorted by offset, throw a TypeError.
        * If there exist any Keyframe object in "processed frames" whose offset member is non-null and less than zero or greater than one, throw a TypeError.
        * Return "processed frames"

    * If the value is an object,

        * Run the procedure defined above (item 1), with "allow lists" as true and "allow offsets" as false. Let the result be called "processed frames".
        * Run the steps under step 2 of http://w3c.github.io/web-animations/#processing-a-frames-argument but *not* the part where we fill in the offsets. We will do that as a later step (see issue #124).
        * Return "processed frames".

    * Otherwise, throw a TypeError.

    (Note that we no longer include the step where we drop keyframes with invalid values now. That should probably have never been added. This should address issue #126.)

4. Define a separate procedure to normalize keyframes. This is called before returning the result from getFrames() and before calculating the result of a keyframe effect.

   It includes the following:
   * Applying spacing modes
   * Merging keyframes
   * Looking up the keyframes referred to be a SharedKeyframeList

   (This is to address the existing issue #124 where offsets get filled in too early.)

5. Make the procedure for calculating the result of a keyframe effect refer to the computed offsets.

6. Define getFrames properly (with reference to item 4 above). This is issue #109 and issue #104. This includes, whether we use [[Set]] or [[DefineOwnProperty]] to add the properties. It also includes converting property names back to IDL names, serializing values from CSS etc.

**Comment by bzbarsky** [comment]
> by applying the procedure here: http://heycam.github.io/webidl/#dictionary-to-es

I think you mean http://heycam.github.io/webidl/#es-to-dictionary

> Use the internal [[Enumerate]] operation on keyframe input to iterate over its properties

This will need to be clearly defined, as you note.

But also, you should decide whether you're actually doing `[[Enumerate]]` and then stepping the iterator (which is what a for-in loop would do, and will consider the object's proto chain) or whether you're using http://www.ecma-international.org/ecma-262/6.0/#sec-enumerableownnames which will ignore the proto chain and only consider properties on the object itself (akin to `Object.keys`).  The latter may be somewhat simpler to specify in that it lands you with a snapshotted list of names to work with.

> [[Get]] each of the properties in "additional property names" in order and do the conversion

Need to clearly specify that each conversion happens before the next `[[Get]]` but otherwise seems ok, as long as you specify the receiver to be passed to `[[Get]]`, presumably as the object itself.

> In both cases perform the conversion with the [TreatNullAs=EmptyString] annotation in effect.

Why?  Is there a behavior difference between "" and "null" for these values?  I guess "null" could actually be a valid value for some property or something?

>  Question: What's the correct way to spec if something is iterable?

What IDL uses in overload resolution is:

1. Let _method_ be the result of `GetMethod(V, @@iterator)`.
2. `ReturnIfAbrupt(method)`.
3. If _method_ is not `undefined` then V is iterable.

> Question: What's the correct way to spec this. [iteration over an object]

The way IDL handles this for sequences normally is via <http://heycam.github.io/webidl/#create-sequence-from-iterable>.  I guess you don't have a specific IDL type `T` because you need the custom processing from item 1 on each iterator return value, but you can pretty much copy/paste this algorithm and replace the steps you want to modify (mostly step 4 substep 3 and step 4 substep 6, I expect).

> This includes, whether we use [[Set]] or [[DefineOwnProperty]] to add the properties. 

You want to use `[[DefineOwnProperty]]`.  The only cases in which they're observably different are cases in which you would not want the setters on Object.prototype that `[[Set]]` would call called, I would think.

**Comment by heycam** [comment]
> But also, you should decide whether you're actually doing [[Enumerate]] and then stepping the iterator (which is what a for-in loop would do, and will consider the object's proto chain) or whether you're using http://www.ecma-international.org/ecma-262/6.0/#sec-enumerableownnames which will ignore the proto chain and only consider properties on the object itself (akin to Object.keys). The latter may be somewhat simpler to specify in that it lands you with a snapshotted list of names to work with.

I'd be OK with Object.keys.  I was wondering whether there were any other object enumerations that use for..in-like enumeration that we'd need to be consistent with, but I don't think there are any?

> > [[Get]] each of the properties in "additional property names" in order and do the conversion
> 
> Need to clearly specify that each conversion happens before the next [[Get]] but otherwise seems ok, as long as you specify the receiver to be passed to [[Get]], presumably as the object itself.

And the CSS property parsing should be done after the conversion of all of these values to `(DOMString or sequence<DOMString>)` or `DOMString`.  Although I think now that we no longer throw an exception on CSS parsing failure, so that shouldn't be detectable, but but conceptually the parsing should be a separate step after the entire JS->IDL conversion process for the arguments of the constructor/animate() is done.

Overall I want to ensure that if/when we introduce support for additional properties like this in the IDL spec, that what we've done with `object` and manual processing here is as close to what we're likely to spec as we can get.  The only issue that I've noticed is that any processing of the `object` value that we define, which will possibly throw exceptions, will happen after we convert the last argument of the `KeyframeEffectReadOnly` constrcutor (the `(unrestricted double or KeyframeTimingOptions)`).  So unless we make that argument `any` and invoke its conversion manually, when we change to the in-build IDL feature to handle additional properties we'll be making a breaking change.  I think the risk of content relying on this is pretty low, though.

Otherwise I think this plan sounds good.

**Comment by birtles** [comment]
Thanks for all your help here. I've made nearly half of these changes to the spec but I won't be able to finish it off and land it until next week.

**Comment by birtles** [comment]
I've made most of these changes now: https://w3c.github.io/web-animations/#processing-a-frames-argument
I still need to write the algorithm for getFrames() and better spec how invalid timing functions are handled.

**Comment by birtles** [comment]
Hopefully these issues should be fixed now. Please let me know if you notice anything amiss. Thanks for all your help with this!

**Comment by bzbarsky** [comment]
@birtles Some nits:

The "conceptual example" IDL for the `Keyframe` dictionary has `composite` nullable while the actual IDL for that dictionary does not.

> or a from property names to sequences of

Extra "a" before "from" should be removed.

> Run the procedure using

The "using" there is a bit weird.  Why's it there?

After calling `EnumerableOwnNames`, if it returned an abrupt completion you probably need to throw the exception in the returned completion record.  This stuff is sadly still not very well defined in IDL.  Not sure whether @heycam has specific language to be used here.

Same thing after calling `[[Get]]`.

In "process a frames argument" step 1, _object_ can't be undefined.  If undefined had been passed, it would get coerced to null during IDL argument processing.

In that same algorithm, it's not clear to me that `ReturnIfAbrupt` makes sense; that's an ES spec concept that might not be applicable here.  See the comments above about exceptions and abrupt completions.

In the iterator case, after we've got a _nextItem_, we should use it somehow.  In particular, we should probably check that it's an object (and throw if not) and then pass it to "process a keyframe-like object".  Passing _object_ to that, as the current text does, doesn't make sense.

**Comment by birtles** [comment]
Thank you for the feedback. I made an attempt at fixing the ReturnIfAbrupt handling (which I agree is awkward and doesn't belong). It will take a few minutes for the spec to be built, but the changeset is here: f8222c487593d28693b31f3571fee61c4e78af23
