### ISSUE TITLE
Make Animation constructor default to document timeline

### ISSUE THREAD

**Issue by birtles** [w3c/web-animations#119]
https://w3c.github.io/web-animations/#issue-df6857e8

**Comment by birtles** [comment]
Issue moved to https://w3c.github.io/web-animations/#issue-0d7a37da

**Comment by birtles** [comment]
The suggestion is basically to change the constructor to:

```webidl
[Constructor (optional AnimationEffectReadOnly? effect = null),
 Constructor (AnimationEffectReadOnly? effect,
              AnimationTimeline? timeline)]
```

That way the following two lines are equivalent:

```webidl
new Animation({ ... });
new Animation({ ... }, document.timeline);
```

Also the following are equivalent:

```webidl
new Animation();
new Animation(null);
new Animation(null, document.timeline);
```

In the less common case where you really want no timeline you would write:

```webidl
new Animation({ ... }, null);
```

If you really want a completely empty Animation you'd have to write:

```webidl
new Animation(null, null);
```

@heycam, @shans, @dstockwell, @tabatkins what do you think?

**Comment by heycam** [comment]
Designing for the common case of using `document.timeline` sounds good.  Another option to consider is:

```webidl
[Constructor (optional AnimationEffectReadOnly? effect = null,
              optional AnimationTimeline? timeline)]
```

This is mostly similar to what you have, but also allows:

```js
new Animation(..., undefined)
```

to be treated as having a missing second optional argument, and then in the prose you can make that mean "use document.timeline".  This can be useful for functions where you want to pass on the arguments to the Animation constructor, or maybe you're getting them from an object.  For example:

```js
var animDetails = [
  { effect: someEffect },
  { effect: someEffect2, timeline: someOtherTimeline }
];
var anims = animDetails.map(details => new Animation(details.effect, details.timeline));
```

where otherwise you would have to write:

```js
var anims = animDetails.map(details => "timeline" in details ?
                              new Animation(details.effect, details.timeline) :
                              new Animation(details.effect));
```

or

```js
var anims = animDetails.map(details =>
  new Animation(details.effect, "timeline" in details ? details.timeline :
                                                        document.timeline));
```

**Comment by birtles** [comment]
Oh nice, that seems better. I think I was under some impression that if you provided defaults for one argument you had to provide them for all the following ones, or that undefined on a nullable became null. Anyway, if that works, that's a lot better! Thanks!

**Comment by graouts** [comment]
I'd like to reopen this issue. While working on implementing Web Animations in WebKit, I've found the way the optional `timeline` parameter is defined in the `Animation` constructor not to be intuitive.

Specifically, I find that calling `new Animation(new KeyframeEffect(…))` and `new Animation(new KeyframeEffect(…), undefined)` and having the first one set `timeline` to `document.timeline` and the other to `undefined` is not intuitive to a JS developer, where omitted values are usually handled as `undefined`. I understand the reason here is that the 99% case is that authors want `document.timeline` as their animation's timeline, at least in the first iteration of the spec where the only concrete timeline is a `DocumentTimeline`. But I would argue that `element.animate()` is the convenience layer in the Web Animations API and that we should not add convenience features to the Animation API, or at least not in a confusing as is the case right now.

My proposed solution is to either:

1. Require an explicit value for the `timeline` parameter to the `Animation` constructor
2. Remove the `timeline` parameter from the `Animation` constructor

I have a preference for 1 but have no objection to 2.
