### ISSUE TITLE
Should activeDuration take into account iterationStart?

### ISSUE THREAD

**Issue by donny-dont** [w3c/web-animations#137]
One thing that popped out to me is that activeDuration is not taking into account iterationStart. If I had an animation with 4 iterations and a duration of 1000ms. I would expect the animation to be complete at 4000ms. If it started at iteration 2 I would expect it to be complete at 2000ms.

Not taking the iterationStart into account seems to misrepresent the actual active duration and screws up the end time calculations.

First time commenting on a spec so I could be totally off base but reading through and trying to implement the API in code the active interval seems incorrect to rely upon for reporting to the client and for figuring out when the animation is complete.

**Comment by donny-dont** [comment]
So just to clarify I would think the following would define activeDuration.

```
activeDuration = max((iterationStart - iterations) * duration, 0);
```

Then endTime would be computed correctly through.

```
endTime = max(delay + activeDuration + endDelay, 0);
```

**Comment by birtles** [comment]
Hi! Thanks for your feedback!

iterationStart is not supposed to affect the duration of an animation, it's just there so that you can start mid-way through an iteration. Also, when combined with iterationComposite (where the result on each iteration changes) it lets you start at a specific iteration.

If you want to define a 4000ms animation and then jump to mid-way into it, you can either seek using the currentTime, or use a negative delay.

So I think the definitions are right but maybe the purpose of iterationStart is unclear?

**Comment by donny-dont** [comment]
Yea I think that might have threw me off a bit. With the first read it seemed more like `iterations` was the number of iterations total so more like an `iterationEnd`. Not sure if that would be useful in the computed timings.

**Comment by birtles** [comment]
I think this definition is correct so I'm going to close this issue. Please re-open if you think there's something missing here.
