### ISSUE TITLE
[web-animations-2] Offset syntax

### ISSUE THREAD

**Issue by caub** [w3c/web-animations#164]
I don't think it's a good idea to mix `offset` between other css properties

```
el.animate([
    { background: '#ff004d', offset: 0 },
    { background: '#ff77ab', offset: 0.20 },
    { background: '#00e756', offset: 0.5 },
    { background: '#29adff', offset: 0.80 },
    { background: '#ff77ab', offset: 1 }
], {
    duration: 2000,
    direction: 'alternate',
    iterations: Infinity
});
```

In comparison below, it's not ideal (you could have both '0.2', '0.20' as keys), but it helps separating concerns

```
el.animate({
    '0': { background: '#ff004d' },
    '0.2': { background: '#ff77ab' },
    '0.5': { background: '#00e756' },
    '0.8': { background: '#29adff' },
    '1': { background: '#ff77ab' }
}, {
    duration: 2000,
    direction: 'alternate',
    iterations: Infinity
});
```

**Comment by Martin-Pitt** [comment]
Keys are strings though and creating offsets programmatically like that would also seem just plain _weird_.

Additionally with JS, object keys are not in any particular guaranteed order, so spitting it out to JSON might turn into a jumbled mess of unreadable frames all over the place.

**Comment by caub** [comment]
```
var o = {
    '0': { background: '#ff004d' },
    '0.2': { background: '#ff77ab' },
    '0.5': { background: '#00e756' },
    '0.8': { background: '#29adff' },
    '1': { background: '#ff77ab' }
}
var steps = new Map(Object.entries(o).map(([k,v])=>[Number(k),v])); // convert back to numbers
for (let [offset, style] of steps) console.log(offset, style)
```

**Comment by birtles** [comment]
I'm not particularly keen on adding yet more possible ways of specifying keyframes (we still need to support the currently specced means since the are shipping in two browsers and the polyfill, so this would simply be adding to that set). However see #148 which extends the existing object-syntax to allow:

```js
{ width: [ '20px', '30px', '50px' ],
  offset: [ 0, 0.2, 1 ] }
```

**Comment by shans** [comment]
I'm not sure this would work - if that's supported, what would
```
{ width: [ '20px', '30px', '50px' ], 
  offset: [ 0, 0.2 ] }
```
do?

One option would be to 'distribute' the offsets and widths separately, so the offsets apply to the first and last keyframes and the '30px' frame is 0.1. This makes
```
{ width: [ '20px', '30px', '50px' ], 
  offset: [ 0, 0.2, 0.4, 0.9 ] }
```
weird though, because that would distribute the 30px keyframe half-way between 0.2 and 0.4 (actually this isn't terrible).

We could also make mismatched offsets an error, but that gets strange if there are multiple property lists of different lengths.

We could just duplicate the last offset value too.

**Comment by caub** [comment]
Ah, that one is at least consistent with the array version, offset is mixed again with css properties.

But I've seen that there are other special keys like `composite`, `easing` for each keyframe, I don't know how my proposal could even handle them

**Comment by birtles** [comment]
@shans: This discussion probably belongs in #148 but I think with regards to:

```js
{ width: [ '20px', '30px', '50px' ], 
  offset: [ 0, 0.2 ] }
```

Your proposal in the IRC log in #148 was that you'd end up extending the offsets array so it becomes `[ 0, 0.2, 0.2 ]`. That's probably not what the author expected&mdash;they probably expected it to become `[ 0, 0.2, 1 ]`&mdash;but it might be better to be consistent than clever. Anyway, we should continue this conversation in #148.

**Comment by birtles** [comment]
This issue was moved to w3c/csswg-drafts#2064
