### ISSUE TITLE
Animatable (a mixin) cannot be used as an argument type

### ISSUE THREAD

**Issue by foolip** [w3c/web-animations#186]
https://w3c.github.io/web-animations/#the-keyframeeffect-interfaces

Here the constructor is:
```WebIDL
[Constructor (Animatable? target,
              object? keyframes,
              optional (unrestricted double or KeyframeEffectOptions) options),
 Constructor (KeyframeEffectReadOnly source)]
```

But `Animatable` is a mixin that's implemented by `Element`. This has the same effect as a `partial interface Element`, and there no instances of `Animatable` itself.

The type would have to be `(Element or CSSPseudoElement)?` instead.

**Comment by birtles** [comment]
See also [Mozilla bug 1241783](https://bugzilla.mozilla.org/show_bug.cgi?id=1241783) where we ended up using a union internally. I think this interface was introduced at @tabatkins suggestion, so if Google is ok with changing this to a union then I think we should just do that.

**Comment by foolip** [comment]
So, I actually didn't look at Web IDL to see if this kind of thing is allowed. @domenic?

**Comment by domenic** [comment]
I'm not very familiar with that part of the spec; you all could go read it to figure out the answer just as well as I could :)

**Comment by bzbarsky** [comment]
The current state of things in IDL is that this is allowed, because mixins are interfaces right now, and the language about what it means to implement an interface is vague enough (due to lack of specific branding bits) that an instance of an interface that has a mixin arguably implements the mixin interface.

As https://bugzilla.mozilla.org/show_bug.cgi?id=1241783#c1 says, once we finally make mixins not be interfaces, I think this IDL should be disallowed, for what it's worth.  Similarly, once we do explicit brand checks this will probably become disallowed unless care is taken to have mixins affect branding.

**Comment by birtles** [comment]
I think we've reached consensus that this should use the union type instead so I've updated the spec accordingly.

**Comment by birtles** [comment]
I guess the type of the `target` attribute should also be a union too.
