### ISSUE TITLE
Expose totalTime on animation object

### ISSUE THREAD

**Issue by aghassemi** [w3c/web-animations#192]
The [animation object ](https://developer.mozilla.org/en-US/docs/Web/API/Animation) returned by `element.animate()` includes a `currentTime` property but nothing to expose the total duration of the animation.

Aside from `infinite` iterations, is there anything in the spec that would prevent knowing the total duration deterministically ahead of time? (are concepts such as streaming or conditional keyframes being considered?) If not, exposing a `totalTime` would be very beneficial. 

Currently we are calculating this by doing:
```
total = (iterations - iterationStart) * duration + delay + endDelay
```

However I am worried that, if this is not exposed naively, we may miss future timing properties/spec changes that may impact total duration.

Our use-case for knowing totalTime is to support `seek(percentage)` where one can seek to a relative point within the animation timeline by providing a percent value. (e.g. `seek(0.5)` to jump to the `middle` of the timeline)

**Comment by birtles** [comment]
Originally the design was the `Animation` objects are just the engine and are ignorant of the content they are driving. However, in order to line up better with `HTMLMediaElement` we added the finishing behavior which meant introducing the concept of the [target effect end](https://w3c.github.io/web-animations/#target-effect-end). Since we have that concept and `finish()` etc. rely on it, I suppose there's no harm in exposing it. I'm not sure if `totalTime`, `endTime`, or `finishTime` is better (although I lean towards `finishTime` for its parallel with `finish()`). However, what's to stop you from just doing `animation.effect.getComputedTiming().endTime` ?

**Comment by aghassemi** [comment]
Thanks @birtles , I will give `animation.effect.getComputedTiming().endTime` a shot, was not aware of it. 

`finishTime` as the name feel right to me.

**Comment by birtles** [comment]
I'm going to close this for now, since this seems possible via existing APIs. Please re-open if you disagree.
