### ISSUE TITLE
CSS display values are not supported

### ISSUE THREAD

**Issue by matsko** [w3c/web-animations#195]
So it turns out that `display` values are totally ignored throughout an animation when `element.animate` is used.

```js
var keyframes = [
  {opacity: 1, display: 'block', offset: 0},
  {opacity: 0, display: 'block', offset: 0.98},
  {opacity: 0.5, display: 'none', offset: 1}
];

// the targetElement should render as hidden, but it shows up as block with opacity=0.5
targetElement.animate(keyframes, { duration: 1000, fill: 'both' });
```

https://jsbin.com/gofeginuvo/edit?html,output

If this is by design then there needs to be some documentation as to why this isn't supported. If it is supported then it's a bug in Chrome and Firefox. 

The other thing to keep in mind is that this may behave differently in polyfill-dependent browsers like Safari / Edge.

**Comment by birtles** [comment]
The `display` is currently not specced as being animatable. It probably never will be for CSS animations / transitions since `display` is also used to trigger/cancel CSS animations/transitions so it would create cyclic dependencies.

In both Firefox and Chrome we tried to make it animatable from Web Animations only but ran into many problems (the `display` property has a lot of special case behavior). I want to try and get it to work again and make `display` animatable from Web Animations but we haven't succeeded in doing that yet so the specs still indicates it is not animatable.

**Comment by tabatkins** [comment]
Yeah, `display` is a special snowflake here; in particular, animating to `display: none` is somewhat... interesting, because it doesn't have a box at that point, so many properties don't apply or have some sort of no-op value.

Using `visibility: hidden` can be a nice compromise most of the time.

**Comment by matsko** [comment]
Excellent. Thank you guys for responding so quick and for providing such a detailed answer to my question.
