### ISSUE TITLE
KeyframeEffect interface's timing attribute should be writable

### ISSUE THREAD

**Issue by hgl** [w3c/web-animations#81]
Should the `KeyframeEffect` interface contain

`inherit attribute AnimationEffectTimingReadonly timing;`

So the `timing` attribute is writable?

Not super fluent in web idl, but is this enough to make attributes of the `timing` attribute writable?

**Comment by shans** [comment]
Setting an attribute as writable doesn't make attributes of the attribute writable. What would need to be in the `KeyframeEffect` interface is something along the lines of
`inherit attribute AnimationEffectTiming timing;`

However, I don't know if this is valid WebIDL.

Overall though, I think this is OK despite the IDL being awkward/wrongish. If you look at the prose associated with the `KeyframeEffect` constructor, there's this in a bullet point:

"`effect.timing` is set to a new `AnimationEffectTiming` object rather than a new `AnimationEffectTimingReadonly` object."

Brian - OK to close this?

**Comment by hgl** [comment]
Ah, yes, it should be `AnimationEffectTiming`. The bullet point doesn't ring a bell until now. :)

**Comment by birtles** [comment]
Yeah, that's right.

(For my own reference, if we ever want to make the timing property itself writeable we'll probably bring part of the <code>AnimationEffectMutable</code> interface forward from level-2, add <code>inherit attribute AnimationEffectTimingReadonly timing</code> to it, then make <code>KeyframeEffect implements AnimationEffectMutable</code>.)
